DEBUG = False
TITLE = 'Bravo'
LOG_PATH = '/var/www/bravo/logs/'
LOG_LINES = 200
DB = 'bravo'
MONGO_URL = 'localhost'
MONGO_PORT = 27017
LOCAL_PORT = 8000
LOCAL_URL = 'http://localhost:%s' % LOCAL_PORT
#PUB_URL = 'http://bravoweb.ca'
PUB_URL = 'http://45.55.14.215' # Test server
#ETAP_API_URL = PUB_URL + '/php/views.php'
ETAP_API_URL = 'http://www.bravoweb.ca/php/views.php'
SECRET_KEY = 'secret'
GSHEET_NAME = 'Bravo Sheets'
